// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoCO2YGRhno2wVqRCF0bctyroAlpzTaU8',
    appId: '1:128395373556:web:c5968db93257fd0aaf67a1',
    messagingSenderId: '128395373556',
    projectId: 'maram-c7fce',
    authDomain: 'maram-c7fce.firebaseapp.com',
    storageBucket: 'maram-c7fce.firebasestorage.app',
    measurementId: 'G-ZYCC7W26XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnXv3g8fU4-NCHgwn1_sxyCAzCroLJvvc',
    appId: '1:128395373556:android:7076653d0077a703af67a1',
    messagingSenderId: '128395373556',
    projectId: 'maram-c7fce',
    storageBucket: 'maram-c7fce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr-IjeDtfUlwplnLTyrCy1SzlFiUTyei8',
    appId: '1:128395373556:ios:ab3e5049d0c842b7af67a1',
    messagingSenderId: '128395373556',
    projectId: 'maram-c7fce',
    storageBucket: 'maram-c7fce.firebasestorage.app',
    iosBundleId: 'com.example.projetttt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr-IjeDtfUlwplnLTyrCy1SzlFiUTyei8',
    appId: '1:128395373556:ios:ab3e5049d0c842b7af67a1',
    messagingSenderId: '128395373556',
    projectId: 'maram-c7fce',
    storageBucket: 'maram-c7fce.firebasestorage.app',
    iosBundleId: 'com.example.projetttt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoCO2YGRhno2wVqRCF0bctyroAlpzTaU8',
    appId: '1:128395373556:web:1f0d9e2547c5421faf67a1',
    messagingSenderId: '128395373556',
    projectId: 'maram-c7fce',
    authDomain: 'maram-c7fce.firebaseapp.com',
    storageBucket: 'maram-c7fce.firebasestorage.app',
    measurementId: 'G-9YLN7VH87W',
  );
}
